# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому перешел на этот плагин. Он тоже хорош :-)

# Создаем продавца
POST http://localhost:8000/api/v1/sellers/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "Ryan",
    "last_name": "Gosling",
    "e_mail": "ryan_gosling@gmail.com",
    "password": "ryan_gosling"
}

###

# Получаем список продавцов
GET http://localhost:8000/api/v1/sellers/ HTTP/1.1

###

# Получаем токен для авторизации
# @name login
POST http://localhost:8000/api/v1/token/
Content-Type: application/json

{
    "email": "ryan_gosling@gmail.com",
    "password": "ryan_gosling"
}

###
@token = {{login.response.body.access_token}}
###

# Получаем одного продавца по его ID (нужна авторизация)
GET http://localhost:8000/api/v1/sellers/1 HTTP/1.1
Authorization: Bearer {{token}}
###

# Удаляем продавца
DELETE http://localhost:8000/api/v1/sellers/1 HTTP/1.1

###

# Обновляем все поля в данных о продавце
PUT http://localhost:8000/api/v1/sellers/1 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Jack",
    "last_name": "Nicholson",
    "e_mail": "ryan_gosling@gmail.com"
}

###

# Обновляем определенные поля в данных о продавце (для PATCH не делал авторизацию)
PATCH http://localhost:8000/api/v1/sellers/1 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Леонид",
    "last_name": "Гайдай"
}

###

# Создаем книгу (нужна авторизация)
POST http://localhost:8000/api/v1/books/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "seller_id": 1,
    "title": "Clean Architecture",
    "author": "Robert Martin",
    "count_pages": 300,
    "year": 2025
}

###

# Получаем список книг
GET http://localhost:8000/api/v1/books/ HTTP/1.1

###

# Получаем одну книгу по ее ID
GET http://localhost:8000/api/v1/books/1 HTTP/1.1

###

# Удаляем книгу
DELETE http://localhost:8000/api/v1/books/1 HTTP/1.1

###

# Обновляем все поля в данных о книге (нужна авторизация)
PUT http://localhost:8000/api/v1/books/1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "seller_id": 1,
    "title": "Clean Code",
    "author": "Robert Martin",
    "year": 2022,
    "pages": 310
}

###


# Обновляем определенные поля в данных о книге (для PATCH не делал авторизацию)
PATCH http://localhost:8000/api/v1/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Mziri",
    "pages": 310
}

###